### ISSUE TITLE
Install of statsmodels 0.9.0 from requirements.txt fails with Python 3.8

### ISSUE THREAD

**Issue by ceharris** [stefmolin/Hands-On-Data-Analysis-with-Pandas#6]
Installing the packages in requirements.txt fails on statsmodels 0.9.0 using Python 3.8. Works fine with Python 3.6 and 3.7.

```
$ python3.8 -m venv venv
$ source venv/bin/activate
(venv) $ python --version
Python 3.8.3
(venv) $ pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5a/4a/39400ff9b36e719bdf8f31c99fe1fa7842a42fa77432e584f707a5080063/pip-20.2.2-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-20.2.2
(venv) $ pip install -r requirements.txt
Collecting git+https://github.com/stefmolin/login-attempt-simulator.git@pandas_book (from -r requirements.txt (line 15))
  Cloning https://github.com/stefmolin/login-attempt-simulator.git (to revision pandas_book) to /private/var/folders/rp/fw34lt290915jy32x3_l58600000gn/T/pip-req-build-bo3g65iq
Collecting git+https://github.com/stefmolin/ml-utils.git@pandas_book (from -r requirements.txt (line 16))
  Cloning https://github.com/stefmolin/ml-utils.git (to revision pandas_book) to /private/var/folders/rp/fw34lt290915jy32x3_l58600000gn/T/pip-req-build-rhx0ctdv
Collecting git+https://github.com/stefmolin/stock-analysis.git@pandas_book (from -r requirements.txt (line 17))
  Cloning https://github.com/stefmolin/stock-analysis.git (to revision pandas_book) to /private/var/folders/rp/fw34lt290915jy32x3_l58600000gn/T/pip-req-build-4us8umnm
Collecting graphviz==0.10.1
  Using cached graphviz-0.10.1-py2.py3-none-any.whl (16 kB)
Collecting imbalanced-learn==0.4.3
  Using cached imbalanced_learn-0.4.3-py3-none-any.whl (166 kB)
Collecting jupyter==1.0.0
  Using cached jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Collecting jupyterlab==0.35.6
  Using cached jupyterlab-0.35.6-py3-none-any.whl (14.8 MB)
Collecting matplotlib==3.0.3
  Using cached matplotlib-3.0.3.tar.gz (36.6 MB)
Collecting numpy==1.16.3
  Using cached numpy-1.16.3.zip (5.1 MB)
Collecting pandas==0.23.4
  Using cached pandas-0.23.4.tar.gz (10.5 MB)
Collecting pandas-datareader==0.7.0
  Using cached pandas_datareader-0.7.0-py2.py3-none-any.whl (111 kB)
Collecting requests==2.21.0
  Using cached requests-2.21.0-py2.py3-none-any.whl (57 kB)
Collecting scikit-learn==0.20.3
  Using cached scikit-learn-0.20.3.tar.gz (11.8 MB)
Collecting scipy==1.2.1
  Using cached scipy-1.2.1.tar.gz (23.1 MB)
Collecting seaborn==0.9.0
  Using cached seaborn-0.9.0-py3-none-any.whl (208 kB)
Collecting sqlalchemy==1.3.3
  Using cached SQLAlchemy-1.3.3.tar.gz (5.9 MB)
Collecting statsmodels==0.9.0
  Using cached statsmodels-0.9.0.tar.gz (12.7 MB)
    ERROR: Command errored out with exit status 1:
     command: /Users/ceharris/git/Hands-On-Data-Analysis-with-Pandas/venv/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rp/fw34lt290915jy32x3_l58600000gn/T/pip-install-mj4t9vyf/statsmodels/setup.py'"'"'; __file__='"'"'/private/var/folders/rp/fw34lt290915jy32x3_l58600000gn/T/pip-install-mj4t9vyf/statsmodels/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/rp/fw34lt290915jy32x3_l58600000gn/T/pip-pip-egg-info-njuosqm7
         cwd: /private/var/folders/rp/fw34lt290915jy32x3_l58600000gn/T/pip-install-mj4t9vyf/statsmodels/
    Complete output (7 lines):
    /private/var/folders/rp/fw34lt290915jy32x3_l58600000gn/T/pip-install-mj4t9vyf/statsmodels/setup.py:477: SyntaxWarning: "is" with a literal. Did you mean "=="?
      if i is "tests":
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rp/fw34lt290915jy32x3_l58600000gn/T/pip-install-mj4t9vyf/statsmodels/setup.py", line 347, in <module>
        from numpy.distutils.misc_util import get_info
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by stefmolin** [comment]
Try installing numpy first and then using the requirements.txt. It looks like statsmodels is trying to use numpy before it is installed, as in [this issue](https://github.com/statsmodels/statsmodels/issues/4635).
